### ISSUE TITLE
Add dates for micro project "Mitmachklima"

### ISSUE THREAD

**Issue by itrich** [section77/chaostreff-scheduler#1]
Can someone please add the following dates for the micro project Mitmachklima?

- 04.10.2021, 17:00 CEST
- 30.11.2021, 17:00 CEST
- 26.01.2022, 17:00 CEST

I can add a template within section77/website on my own. Thank you!

**Comment by j-keck** [comment]
This is only a one-time event. 
We can create it directly in the website repo: https://github.com/section77/website/tree/master/content/kalender.
Just copy any "contents.lr" as a reference.

Should I do it, or will you do it?

**Comment by itrich** [comment]
Thank you for the hint, I'll create the events myself.
